# Feature Selection 001 - Dropping Constant

### sklearn.feature_selection.VarianceThreshold¶
Will remove all the features having the criteria of the treshold

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
X = [[0, 2, 0, 3], [0, 1, 4, 3], [0, 1, 1, 3]]

In [4]:
from sklearn.feature_selection import VarianceThreshold


In [5]:
selector = VarianceThreshold(threshold=0)
selector.fit_transform(X)

array([[2, 0],
       [1, 4],
       [1, 1]])

In [6]:
X

[[0, 2, 0, 3], [0, 1, 4, 3], [0, 1, 1, 3]]

In [15]:
X1 = np.random.randint(1,100,10)
X2 = np.random.randint(200,300,10)
X3 = np.zeros(10)
X4 = np.ones(10)

In [16]:
X1,X2

(array([88, 93, 75, 76, 49, 92, 34, 49, 26, 36]),
 array([290, 236, 255, 267, 246, 202, 256, 229, 210, 275]))

In [22]:
X = np.array([X1,X2,X3,X4]).T

In [23]:
X

array([[ 88., 290.,   0.,   1.],
       [ 93., 236.,   0.,   1.],
       [ 75., 255.,   0.,   1.],
       [ 76., 267.,   0.,   1.],
       [ 49., 246.,   0.,   1.],
       [ 92., 202.,   0.,   1.],
       [ 34., 256.,   0.,   1.],
       [ 49., 229.,   0.,   1.],
       [ 26., 210.,   0.,   1.],
       [ 36., 275.,   0.,   1.]])

In [24]:
data = pd.DataFrame(X)

In [25]:
data.head()

0      1    2    3
0  88.0  290.0  0.0  1.0
1  93.0  236.0  0.0  1.0
2  75.0  255.0  0.0  1.0
3  76.0  267.0  0.0  1.0
4  49.0  246.0  0.0  1.0

In [26]:
from sklearn.feature_selection import VarianceThreshold

In [27]:
selector = VarianceThreshold(threshold=0)

In [28]:
selector.fit(data)

VarianceThreshold(threshold=0)

In [30]:
selector.get_support()

array([ True,  True, False, False])

In [32]:
const_cols = [column for column in data.columns if column not in data.columns[selector.get_support()] ]

In [33]:
const_cols

[2, 3]

In [34]:
data.drop(const_cols,axis=1)

0      1
0  88.0  290.0
1  93.0  236.0
2  75.0  255.0
3  76.0  267.0
4  49.0  246.0
5  92.0  202.0
6  34.0  256.0
7  49.0  229.0
8  26.0  210.0
9  36.0  275.0